# -------------------------------------------------------------------------------------------------
# This workflow is meant to be copied to the preview repo, in order to handle the actual GitHub
# Pages deployment, along with any other accessory operation, like commenting on a PR.
# Remember to edit the placeholder env variables below to best suit your needs.
# -------------------------------------------------------------------------------------------------

name: Deploy previews and comment on PR
on:
  repository_dispatch:
    types: [deploy-preview]
    inputs:
      action:
        description: 'The action that was performed, either "deploy" or "remove"'
        required: true
        type: string
      date:
        description: 'The date of the commit that was pushed'
        required: true
        type: string
      event_name: 
        description: 'The name of the event that triggered the workflow'
        required: true
        type: string
      path:
        description: 'The path of the preview that has been edited'
        required: true
        type: string
      preview_branch:
        description: 'The name of the branch that hosts the previews'
        required: true
        type: string
      ref:
        description: 'The ref to deploy'
        required: true
        type: string
      source_repo:
        description: 'The repository to comment to, in the Owner/Name format'
        required: true
        type: string
      source_repo_token:
        description: 'The token to comment to the source repo'
        required: true
        type: string
      version:
        description: 'The version of EndBug/pages-preview that triggered the workflow'
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy previews to GitHub Pages
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v1

  comment:
    name: Comment on the original PR
    needs: deploy
    if: ${{ startsWith(inputs.event_name, 'pull_request') }}

    uses: EndBug/pages-preview@${{ inputs.version }}/.github/workflows/comment.yml
    with:
      action: ${{ inputs.action }}
      date: ${{ inputs.date }}
      preview_branch: ${{ inputs.preview_branch }}
      preview_url: ${{ needs.deploy.outputs.page_url }}/${{ inputs.path }}
      source_repo: ${{ inputs.source_repo }}
    secrets:
      repo_token: ${{ inputs.source_repo_token }}
