# -------------------------------------------------------------------------------------------------
# This workflow is meant to be copied to the preview repo, in order to handle the actual GitHub
# Pages deployment, along with any other accessory operation, like commenting on a PR.
# Remember to edit the placeholder env variables below to best suit your needs.
# -------------------------------------------------------------------------------------------------

name: Deploy previews and comment on PR
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'The action that was performed, either "deploy" or "remove"'
        required: true
        type: string
      date:
        description: 'The date of the commit that was pushed'
        required: true
        type: string
      event_name: 
        description: 'The name of the event that triggered the workflow'
        required: true
        type: string
      path:
        description: 'The path of the preview that has been edited'
        required: true
        type: string
      pr_number:
        description: 'The number of the pull request that triggered the workflow, use 0 if not a PR.'
        required: true
        type: string
      preview_branch:
        description: 'The name of the branch that hosts the previews'
        required: true
        type: string
      ref:
        description: 'The ref to deploy'
        required: true
        type: string
      source_repo:
        description: 'The repository to comment to, in the Owner/Name format'
        required: true
        type: string
      source_repo_token:
        description: 'The token to comment to the source repo'
        required: true
        type: string
      version:
        description: 'The version of EndBug/pages-preview that triggered the workflow'
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # VERSION: update before changing the major version
  version-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check version
      run: |
        if [ "${{ github.event.inputs.version }}" != "v1" ]; then
          echo "This workflow is meant to be used with EndBug/pages-preview@v1, please update your action."
          exit 1
        fi

  deploy:
    name: Deploy previews to GitHub Pages
    runs-on: ubuntu-latest
    needs: version-check

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v1

  comment:
    name: Comment on the original PR
    needs: [version-check, deploy]
    if: ${{ startsWith(inputs.event_name, 'pull_request') && inputs.pr_number != 0 }}

    # VERSION: update before changing the major version
    uses: EndBug/pages-preview/.github/workflows/comment.yml@v1
    with:
      action: ${{ inputs.action }}
      date: ${{ inputs.date }}
      pr_number: ${{ inputs.pr_number }}
      preview_branch: ${{ inputs.preview_branch }}
      preview_url: ${{ needs.deploy.outputs.page_url }}/${{ inputs.path }}
      source_repo: ${{ inputs.source_repo }}
      version: ${{ inputs.version }}
    secrets:
      repo_token: ${{ inputs.source_repo_token }}
