# -------------------------------------------------------------------------------------------------
# This workflow is supposed to be re-used in your own deployment workflow.
# To do this, read the instructions in the README.md file.
# -------------------------------------------------------------------------------------------------

name: Push to the preview repo
on:
  workflow_call:
    inputs:
      build_dir: 
        description: The directory in which the website has been built. Should be written as a/b/c
        type: string
        required: true
      preview_repo:
        description: The repository to push previews to, in the Owner/Name format
        type: string
        required: true

      commit_author_name:
        description: The name of the author of the resulting commit
        type: string
        default: GitHub Actions
        required: false
      commit_author_email:
        description: The email of the author of the resulting commit
        type: string
        default: 41898282+github-actions[bot]@users.noreply.github.com
        required: false
      preview_branch:
        description: The name of the branch that hosts the previews
        type: string
        default: gh-pages
        required: false

    secrets:
      preview_token:
        description: Token to access the preview repo
        required: true

# Note: when running a reusable workflow, the github context is associated with the caller repo.
jobs:
  push:
    runs-on: ubuntu-latest
    concurrency: deploy/${{ github.repository }}/${{ startsWith(github.event_name, 'pull_request') && 'pr' || 'branch' }}
    steps:
      - name: Parse what the action to perform
        run: ./lib/parse_action.sh
        shell: bash
        id: parse
        # outputs: action, path
        env:
          EVENT_NAME: ${{ github.event_name }}
          EVENT_PAYLOAD: ${{ toJSON(github.event) }}
          REPO_NAME: ${{ github.repository }}

      - name: Set up the preview repo
        if: ${{ steps.parse.action != 'none' }}
        run: |
          cd ../..
          gh repo clone ${{ inputs.preview_repo }}
          cd preview
          git config --global user.name ${{ inputs.commit_author_name }}
          git config --global user.email ${{ inputs.commit_author_email }}
          echo "GIT_COMMITTER_NAME=GitHub Actions" >> $GITHUB_ENV
          echo "GIT_COMMITTER_EMAIL=41898282+github-actions[bot]@users.noreply.github.com" >> $GITHUB_ENV
          git remote set-url origin https://git:${{ secrets.preview_token }}@github.com/${{ inputs.preview_repo }}.git
          git checkout ${{ inputs.preview_branch }}

      - name: Copy the build directory to the destination and commit the changes
        if: ${{ steps.parse.action == 'deploy' }}
        run: |
          git rm "${{ steps.parse.path }}" -r
          cp "${{ github.workspace }}/${{ inputs.build_dir }}" "${{ steps.parse.path }}" -r
          git add "${{ steps.parse.path }}"
          git commit --message="ci: deploy preview for ${{ steps.parse.path }}"
          git push origin ${{ inputs.preview_branch }}

      - name: Remove the destination directory and commit the changes
        if: ${{ steps.parse.action == 'remove' }}
        run: |
          git rm "${{ steps.parse.path }}" -r
          git commit --message="ci: remove preview for ${{ steps.parse.path }}"
          git push origin ${{ inputs.preview_branch }}
        
